# Generated by Django 3.2.5 on 2023-05-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short_code', models.CharField(max_length=15, unique=True)),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
