# Generated by Django 3.2.5 on 2023-05-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_apps', '0002_redirectmodel_visit_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirectmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='redirectmodel',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
